### ISSUE TITLE
Draft Proposal development

### ISSUE THREAD

**Issue by mahm00d27** [bcgov/opho-cdr-shiny#13]
Draft proposal report is due 10 May 2022 at 6pm. Share with Daniel.

**Comment by chendaniely** [comment]
Comments (since I can't leave them on the actual PDF). feel free to edit the bullet points `-` into tasks `- [ ]` if that might be useful for you.

Intro:

- [x] Define jargon terms: prevalence, incidence, incidence rate, prevalence rate, rates
- [x] Define how the geographies are broken down (like you did in your presentation)
- [x] Just like your presentation, introduce your partner and the work they're doing. It seems the last paragraph can be swapped with the second since it talks about OBCPH?
- [x] Reference Figure 1 in your text (if you're using LaTeX you can do this with `ref{}`

Data Science Techniques

- [x] "Data Science Techniques" and "dashboard" is a stacked header, you need to put text between them. Use the paragraph to introduce all the methods you'll be using, and use the subheadings to go into detail.
- [x] Temporal Modeling: cite and reference the paper that you will be basing the spatial temporal model off of.
- [x] Talk about the autocorrelations about why you are fitting a spatial _and_ temporal model.
- [x] What other techniques can you try with spatial-temporal models that you can compare your bayesian results with? models in isolation are not useful if there's no reference baseline to compare it with.
- [x] Define the differences between the models you will be fitting (AR1,RW1, and RW2)

Conclusion

- [x] Reference your Figure 2.
- [x] Just like in the QA portion of the presentation: talk about how you think (or know) OBCPHO will use this dashboard. Why do you think this will be helpful
- [x] In general: for each of your techniques, talk about how you know your product will be "done". Any certain milestones you are looking for throughout the process?

General:

- [x] Your figures + captions should be able to be standalone from the rest of the document. They should also be referenced in the text if someone wants more context. The caption should describe everything you want the reader to get out of it (i.e., you need a lot more text in the captions to the point where it seems redundant)
    - i.e., what am I supposed to be looking at in Figure 1? what do you want me to get out of that figure?

**Comment by jennifer-hoang** [comment]
Daniel's Feedback Round 2:

Figure 1
- [x] More detail for figure 1 (explain each panel, filters, mock figures)

Data science techniques section:
- [x] Mention descriptive statistics

Conclusion
- [x] Mention why we're not using spatiotemporal model (complexity in time frame, missing data)

Overall
- [x] Update spatiotemporal trends -> temporal trends
