### ISSUE TITLE
Meeting Agenda for 2022-06-03

### ISSUE THREAD

**Issue by jessie14** [bcgov/opho-cdr-shiny#21]
## Agenda Items:
- [ ] Aim to finalize product in next 2 weeks
- [ ] Discuss how to integrate modelled data into dashboard
    - As a separate tab or toggle switches in existing tabs ?

### Dashboard Questions:
- [x] How many decimals should we round confidence intervals to? (Some intervals are small and will round to the rate itself)
- [x] Should we use existing CI data (not modelled data) for error bars / confidence intervals?
- [x] Data dictionary variables different from table column names

### Modeling Questions:
- Follow-up: With the current gamma model, 84% of incidence rate data, 91% of HSC prevalence rate data, and 98% of life prevalence rate data were able to be modelled.
- Tweedie distribution can accommodate 0 values for rare diseases but INLA implementation is experimental. Would it still be useful to generate these models?

### Action Items:
- [ ] Reminder : next week's meeting moved to Thursday June 9,  11am

**Comment by jennifer-hoang** [comment]
## Notes:

### Data Dictionary: 
- [x] Match with the variable names in downloadable dataset headers

### Data table:
- [x] Keep Numerator and Denominator because it changes depending on the rate (number of new cases and population at risk for incidence, total number and population for prevalence)
- [x] Year: clarify and display as fiscal year when possible (2001/02)
- [x] Decimal points: reduce to 2 decimals for CIs
- [x] Variance columns: drop it from the display but keep it in the download data 

### Info Tab:
- [x] Henry/Kayla to review information tabs before final product

### By Disease:
- [x] Average CI rate box: HAs have different populations - try median rate
- [x] Health Region: change to Health Boundaries

### By Region
- [ ] Keep layout design consistent with By Disease
- [x] Add Y-axis from zero toggle
- [x] Top Boxes: show region's most prevalent conditions (top 4) in the last year
- [x] Map: consider removing to make space for more diseases
- [x] No limit on number of diseases selected

### Model Integration
- [x] Toggle to turn on smoothing (show line without confidence intervals), but should be greyed out when Male/Female are selected
- [x] Have smoothened line chart, but leave original data for the bar plot

### Model
- [x] Try setting zeroes to very small values (100* smaller than smallest rate)
